# Generated by Django 2.2.6 on 2019-10-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='desig',
            field=models.CharField(choices=[('V', 'Volunteer'), ('F', 'Faculty')], default='V', max_length=1),
        ),
    ]
