# Generated by Django 2.2.6 on 2020-06-21 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassworkHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cw', models.TextField(blank=True, max_length=255)),
                ('hw', models.TextField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True, max_length=255)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Calendar')),
            ],
            options={
                'verbose_name': 'ClassWork/HomeWork',
                'verbose_name_plural': 'ClassWork/HomeWork',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('feedback', models.TextField(max_length=1023)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('hw_done', models.BooleanField(default=False, verbose_name='HomeWork Done')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Calendar')),
            ],
            options={
                'verbose_name': 'Student Attendence',
                'verbose_name_plural': 'Students Attendence',
            },
        ),
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Student Schedule',
                'verbose_name_plural': 'Students Schedule',
            },
        ),
        migrations.CreateModel(
            name='UpdateScheduleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('approved', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('by_admin', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAttendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('extra', models.BooleanField(default=False)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Calendar')),
            ],
            options={
                'verbose_name': 'Volunteer Attendence',
                'verbose_name_plural': 'Volunteers Attendence',
            },
        ),
        migrations.RenameModel(
            old_name='Volunteer_schedule',
            new_name='VolunteerSchedule',
        ),
        migrations.AlterUniqueTogether(
            name='student_attended_on',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='student_attended_on',
            name='date',
        ),
        migrations.RemoveField(
            model_name='student_attended_on',
            name='sid',
        ),
        migrations.AlterUniqueTogether(
            name='student_schedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='student_schedule',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='student_schedule',
            name='sid',
        ),
        migrations.AlterUniqueTogether(
            name='volunteer_attended_on',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='volunteer_attended_on',
            name='date',
        ),
        migrations.RemoveField(
            model_name='volunteer_attended_on',
            name='roll_no',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Section'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.CharField(choices=[('eng', 'English'), ('hin', 'Hindi'), ('mat', 'Mathematics'), ('sci', 'Science'), ('mab', 'Mental Ability')], default='hin', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Alternate Email'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='batch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact_no',
            field=models.CharField(max_length=13, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='desig',
            field=models.CharField(choices=[('Co-Convenor', (('mcoco', 'Math Co-Convenor'), ('ecoco', 'English Co-Convenor'), ('hcoco', 'Hindi Co-Convenor'), ('scoco', 'Science Co-Convenor'), ('9coco', '9-10 Co-Convenor'), ('navcoco', 'Navodaya Co-Convenor'))), ('Convenor', (('mco', 'Math Convenor'), ('eco', 'English Convenor'), ('hco', 'Hindi Convenor'), ('sco', 'Science Convenor'), ('9co', '9-10 Convenor'), ('navco', 'Navodaya Convenor'))), ('jac', 'Jagrati Advisory Commitee'), ('v', 'Volunteer')], default='v', max_length=5, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='street_address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 2'),
        ),
        migrations.DeleteModel(
            name='Cw_hw',
        ),
        migrations.DeleteModel(
            name='Student_attended_on',
        ),
        migrations.DeleteModel(
            name='Student_schedule',
        ),
        migrations.DeleteModel(
            name='Volunteer_attended_on',
        ),
        migrations.AddField(
            model_name='volunteerattendence',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Volunteer'),
        ),
        migrations.AddField(
            model_name='updateschedulerequest',
            name='previous_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_schedule', to='home.Schedule'),
        ),
        migrations.AddField(
            model_name='updateschedulerequest',
            name='updated_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_schedule', to='home.Schedule'),
        ),
        migrations.AddField(
            model_name='updateschedulerequest',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Volunteer'),
        ),
        migrations.AddField(
            model_name='studentschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Schedule'),
        ),
        migrations.AddField(
            model_name='studentschedule',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
        migrations.AddField(
            model_name='studentattendence',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student', verbose_name='Student Name'),
        ),
        migrations.AddField(
            model_name='classworkhomework',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerattendence',
            unique_together={('roll_no', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='studentschedule',
            unique_together={('sid', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendence',
            unique_together={('sid', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='classworkhomework',
            unique_together={('date', 'section')},
        ),
    ]
