# Generated by Django 2.2.6 on 2020-07-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200621_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='profile_image',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
