# Generated by Django 2.2.6 on 2020-07-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_volunteer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='profile_image',
            field=models.ImageField(default='logo.png', upload_to='profile_pics'),
        ),
    ]
