# Generated by Django 2.2.13 on 2021-04-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('thumb_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='misc/initiatives')),
            ],
        ),
    ]
