# Generated by Django 2.2.13 on 2021-01-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('school_class', models.IntegerField()),
                ('village', models.CharField(choices=[('G', 'Gadheri'), ('M', 'Mehgawan'), ('C', 'Chanditola'), ('A', 'Amanala'), ('S', 'Suarkol')], max_length=3)),
                ('contact_no', models.CharField(blank=True, max_length=13)),
                ('guardian_name', models.CharField(blank=True, max_length=30)),
                ('restricted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_schedules', to='home.Schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_schedules', to='students.Student')),
            ],
            options={
                'verbose_name': 'Student Schedule',
                'verbose_name_plural': 'Students Schedule',
                'unique_together': {('student', 'day')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('hw_done', models.BooleanField(default=False, verbose_name='HomeWork Done')),
                ('cal_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='home.Calendar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='students.Student')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Students Attendance',
                'unique_together': {('student', 'cal_date')},
            },
        ),
    ]
