# Generated by Django 2.2.13 on 2021-03-09 15:50

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='students/profile_pics'),
        ),
        migrations.AlterField(
            model_name='studentschedule',
            name='day',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
