# Generated by Django 2.2.13 on 2020-12-22 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, max_length=255)),
                ('class_scheduled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Calendar',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('subject', models.CharField(choices=[('eng', 'English'), ('hin', 'Hindi'), ('mat', 'Mathematics'), ('sci', 'Science'), ('mab', 'Mental Ability')], max_length=3)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Section')),
            ],
            options={
                'unique_together': {('day', 'section')},
            },
        ),
        migrations.CreateModel(
            name='ClassworkHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_be_taught', models.TextField(blank=True, max_length=1023)),
                ('subject_taught', models.CharField(choices=[('eng', 'English'), ('hin', 'Hindi'), ('mat', 'Mathematics'), ('sci', 'Science'), ('mab', 'Mental Ability')], max_length=3)),
                ('cw', models.TextField(blank=True, max_length=1023)),
                ('hw', models.TextField(blank=True, max_length=1023)),
                ('comment', models.TextField(blank=True, max_length=1023)),
                ('cal_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Calendar')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Section')),
            ],
            options={
                'verbose_name': 'ClassWork/HomeWork',
                'verbose_name_plural': 'ClassWork/HomeWork',
                'unique_together': {('cal_date', 'section')},
            },
        ),
    ]
