# Generated by Django 2.2.13 on 2020-12-22 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig_id', models.CharField(max_length=10, unique=True, verbose_name='Designation ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_desig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteers.Designation')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=8, unique=True, verbose_name='Roll Number')),
                ('batch', models.IntegerField()),
                ('programme', models.CharField(choices=[('bt', 'B.Tech'), ('mt', 'M.Tech'), ('phd', 'PhD'), ('bd', 'B.Des'), ('md', 'M.Des')], max_length=3)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('active', models.BooleanField(default=True)),
                ('desig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteers.Designation')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateScheduleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('approved', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('by_admin', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('new_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_sch_requests_to', to='home.Schedule')),
                ('previous_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_sch_requests_from', to='home.Schedule')),
                ('volun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_sch_requests', to='volunteers.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volun_schedules', to='home.Schedule')),
                ('volun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volun_schedules', to='volunteers.Volunteer')),
            ],
            options={
                'verbose_name': 'Volunteer Schedule',
                'verbose_name_plural': 'Volunteers Schedule',
                'unique_together': {('volun', 'day')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('extra', models.BooleanField(default=False)),
                ('cal_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volun_attendance', to='home.Calendar')),
                ('volun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volun_attendance', to='volunteers.Volunteer')),
            ],
            options={
                'verbose_name': 'Volunteer Attendance',
                'verbose_name_plural': 'Volunteers Attendance',
                'unique_together': {('volun', 'cal_date')},
            },
        ),
    ]
